import torch
import torch.nn as nn
from torch import Tensor
from ..utils import one_hot, activation

class CVAE(nn.Module):

  class Encoder(nn.Module): 
    """
    The encoder takes at point in image space and maps it to not a point, 
    but a distribution p(z|x) in the latent space, this is called the posterior
    distribution, which is intractable. In Kingma's paper, he just simplified 
    it to be a diagonal Gaussian q_phi (z|x), but in reality this can be anything. 
    """

    def __init__(self, **kwargs): 
      super().__init__()
      dimensions = kwargs["dimensions"] 
      activations = kwargs["activations"]
      normalizations = kwargs["normalizations"]
      self.n_classes = kwargs["n_classes"]

      self.fc_maps = nn.Sequential() 
      for i in range(len(dimensions) - 2): 
        idim, odim = dimensions[i], dimensions[i+1] 
        self.fc_maps.append(nn.Linear(idim, odim)) 
        if normalizations[i]: 
          self.fc_maps.append(nn.BatchNorm1d(odim))
        self.fc_maps.append(activation(activations[i]))  
      
      # final pair of layers
      self.fc_mu = nn.Linear(dimensions[-2], dimensions[-1]) 
      self.fc_logvar = nn.Linear(dimensions[-2], dimensions[-1]) 

    def forward(self, x: Tensor, y: Tensor): 
      # x is already flattened
      y = one_hot(y, self.n_classes)
      input = torch.cat([x, y], dim=1)

      input = self.fc_maps(input)
      mu = self.fc_mu(input) 
      logvar = self.fc_logvar(input)
      return mu, logvar

  class Decoder(nn.Module): 
    """
    Decoder takes a point generated by the distribution in the latent space, 
    and maps it back to image space. 
    """

    def __init__(self, **kwargs): 
      super().__init__()
      dimensions = kwargs["dimensions"] 
      activations = kwargs["activations"]
      normalizations = kwargs["normalizations"]
      self.n_classes = kwargs["n_classes"]
      self.model = nn.Sequential() 
      
      for i in range(len(dimensions) - 1): 
        self.model.append(nn.Linear(dimensions[i], dimensions[i+1])) 
        if normalizations[i]: 
          self.model.append(nn.BatchNorm1d(dimensions[i+1]) )
        self.model.append(activation(activations[i]))

    def forward(self, z, y): 
      y = one_hot(y, self.n_classes)
      input = torch.cat([z, y], dim=1) 
      return self.model(input)

  def __init__(self, input_shape, encoder, decoder):
    super().__init__() 
    self.encoder = self.Encoder(**encoder)
    self.decoder = self.Decoder(**decoder)
    self.latent_dim = int(encoder["dimensions"][-1]) 
    self.input_shape = input_shape

  def encode(self, x, y): return self.encoder(x, y) 
  def decode(self, z, y): return self.decoder(z, y)

  def reparameterize(self, mu, logvar):
    """
    Sample a point from p(z|x), which is a Gaussian RV
    """
    stdev = torch.exp(0.5*logvar)
    eps = torch.randn_like(stdev)
    return mu + eps*stdev

  def forward(self, x, y):
    """
    1. Encode x to compute conditional distribution q_phi (z|x) 
    2. Sample from p(z|x) using reparameterization trick. 
    3. Decode to get p(x|z). 
    Just a composition of the encoder, reparamterization, and decoding. 
    """
    x = torch.flatten(x, start_dim=1)
    mu, logvar = self.encoder(x, y)
    z = self.reparameterize(mu, logvar)
    x_recon = self.decoder(z, y)
    x_recon = x_recon.reshape(-1, *self.input_shape)
    return x_recon, mu, logvar



