import torch
import torch.nn as nn
import torch.nn.functional as F

def init_loss(cfg_loss: dict):
  
  match cfg_loss["name"]:
    case 'mse' | 'l2':
      return MSE()
    case 'cross_entropy' | 'ce':
      return CrossEntropy()
    case 'elbo': 
      return ELBO()
    case _:
      raise Exception("Loss not implemented.")


class Loss(nn.Module):
  """Base loss class"""
  def __init__(self):
    super().__init__()
  
  def forward(self, pred, target):
    raise NotImplementedError("Subclass must implement forward method")

class MSE(Loss):
  """Mean Squared Error Loss (L2 Loss)"""
  def __init__(self, reduction='sum'):
    super().__init__()
    self.reduction = reduction
  
  def forward(self, pred, target):
    return F.mse_loss(pred, target, reduction=self.reduction)


class CrossEntropy(Loss):
  """Cross Entropy Loss for classification"""
  def __init__(self, weight=None, reduction='sum', label_smoothing=0.0):
    super().__init__()
    self.weight = weight
    self.reduction = reduction
    self.label_smoothing = label_smoothing
  
  def forward(self, pred, target):
    return F.cross_entropy(pred, target, weight=self.weight, reduction=self.reduction)

class ELBO(Loss): 
  """
  Computes the loss = -ELBO = Negative Log-Likelihood + KL Divergence. 
  Note that this is just a balance between how close our posterior is 
  to our modeled prior (q_phi(z|x) vs p(z)), and the NLL of the samples 
  x generated by z. Eq (10) in Kingma's paper
  """
  def __init__(self): 
    super().__init__()
    ...

  def forward(self, recon_x, x, mu, logvar): 
    BCE = F.binary_cross_entropy(recon_x, x, reduction='sum') # BCE = -Negative Log-likelihood
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()) # KL Divergence b/w q_\phi(z|x) || p(z)
    return BCE + KLD


