name: ""                          # run name. If empty, then uses current timestamp n_gpus: 0                         # 0 = cpu, 1 = cuda:0, >1 = multi-gpu setup
seed: 0
n_gpus: 1                         # 0 = cpu, 1 = cuda:0, >1 = multi-gpu setup

run: 
  dataset: 
    name: "mnist"                        # name of the dataset
    split: [0.6, 0.2, 0.2]          # train/val/test split. If the split is provided, then it ignores this. If there is already a train/test split, then we divide the train set into train/val split according to the ratio of the first two elements of the tuple. 
    train: 
      subsample: 1.0                # To speed up train runs for initial debugging. Either an int > 1 representing number of samples to truncate from, or float in [0, 1] representing portion of dataset to train on
      batch_size: 32
      num_workers: 1
      pin_memory: True
      shuffle: True
      # augmentation: []              # potential augmentation 
    val: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True
    test: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True

  epoch: 0
  total_epochs: 50

  model:                              # each model has different hyperparameters, so case-by-case  
    name: "cvae"    # determines the class it will instantiate 
    input_shape: [1, 28, 28]
    encoder: 
      name: 
      n_classes: 10
      dimensions: [794, 400, 200, 20, 10]     # note that it's 794 = 784 + 10
      activations: ["relu", "relu", "relu", ""] 
      normalizations: [False, False, False, False]
    decoder: 
      name: 
      n_classes: 10
      dimensions: [20, 20, 200, 400, 784] # should be 20 = 10 + 10
      activations: ["relu", "relu", "relu", "sigmoid"]
      normalizations: [False, False, False, False]
    checkpoint: ""

  loss: 
    name: "elbo"
    l1: 0.0                         # l1 loss, added directly to weights of model
    # add hyperparameters here

  optimizer: 
    name: "adam"                        # sgd, adam 
    checkpoint: ""                  # checkpoint path to optimizer
    lr: 1e-3                        # learning rate
    momentum: 0.0                   # momentum, only relevant for SGD
    betas: [0.9, 0.999]             # betas, relevant only for Adam
    weight_decay: 0.0

log:
  savedir: ""                       # dummy, will be overrided by saved/name 
  track: 
    every: 1 
  checkpoint: 
    every: 5 
    model: True 
    optimizer: True
  diagnose: 
    every: 1
    weights: True 
    gradients: True 
    sample_digits: True 
    reconstruct: True  
    interpolate: True  
    visualize_latent_space: True
  wandb: 
    enabled: True
    entity: "bahngmc-duke-university" 
    project: ""
