name: ""                          # run name. If empty, then uses current timestamp
seed: 0
n_gpus: 1                         # 0 = cpu, 1 = cuda:0, >1 = multi-gpu setup

run: 
  dataset: 
    name: "shakespeare"
    block_size: 64
    split: [0.6, 0.2, 0.2]          # train/val/test split. If the split is provided, then it ignores this. If there is already a train/test split, then we divide the train set into train/val split according to the ratio of the first two elements of the tuple. 
    train: 
      subsample: 1.0                # To speed up train runs for initial debugging. Either an int > 1 representing number of samples to truncate from, or float in [0, 1] representing portion of dataset to train on
      batch_size: 12
      num_workers: 1
      pin_memory: True
      shuffle: True
      # augmentation: []              # potential augmentation 
    val: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True
    test: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True
    vocab_size: 91

  epoch: 0
  total_epochs: 10

  model:                              # each model has different hyperparameters, so case-by-case  
    name: "gpt2"
    checkpoint: ""
    block_size: 64 
    vocab_size: 91
    embed_dim: 128
    n_layer: 4
    attention_block: 
      n_head: 4 

  loss: 
    name: "ce"
    l1: 0.0                         # l1 loss, added directly to weights of model
    # add hyperparameters here

  optimizer: 
    name: "adam"                        # sgd, adam 
    checkpoint: ""                  # checkpoint path to optimizer
    lr: 6e-4                        # learning rate
    momentum: 0.0                   # momentum, only relevant for SGD
    betas: [0.9, 0.95]             # betas, relevant only for Adam
    weight_decay: 0.1

log:
  savedir: ""                       # dummy, will be overrided by saved/name 
  track: 
    every: 1 
  checkpoint: 
    every: 1
    model: True 
    optimizer: True
  diagnose: 
    every: 1
    weights: True 
    gradients: True 
  wandb: 
    enabled: True
    entity: "bahngmc-duke-university" 
    project: "689"


