name: ""                          # run name. If empty, then uses current timestamp
n_gpus: 1                         # 0 = cpu, 1 = cuda:0, >1 = multi-gpu setup
seed: 0


run: 
  dataset: 
    name: "four_gaussians"                        # name of the dataset
    split: [0.6, 0.2, 0.2]          # train/val/test split. If the split is provided, then it ignores this. If there is already a train/test split, then we divide the train set into train/val split according to the ratio of the first two elements of the tuple. 
    train: 
      subsample: 1.0                # To speed up train runs for initial debugging. Either an int > 1 representing number of samples to truncate from, or float in [0, 1] representing portion of dataset to train on
      batch_size: 32
      num_workers: 1
      pin_memory: True
      shuffle: True
      # augmentation: []              # potential augmentation 
    val: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True
    test: 
      subsample: 1.0
      batch_size: 32
      num_workers: 1
      pin_memory: True

  epoch: 0
  total_epochs: 50
  dequantize: False

  model:
    name: "nice"
    checkpoint: "" 
    input_shape: [2]
    n_coupling_layers: 20
    scaling_layer: 

    coupling_layer: 
      mlp: 
        dimensions: [2, 50, 50, 50, 50, 50, 50, 50, 50, 2]
        normalizations: [False, False, False, False, False, False, False, False, False]
        activations: ["leaky_relu", "leaky_relu", "leaky_relu", "leaky_relu", "leaky_relu", "leaky_relu", "leaky_relu", "leaky_relu", ""]

  loss: 
    name: "ce"
    l1: 0.0                         # l1 loss, added directly to weights of model
    # add hyperparameters here

  optimizer: 
    name: "adam"                        # sgd, adam 
    checkpoint: ""                  # checkpoint path to optimizer
    lr: 1e-3                        # learning rate
    momentum: 0.0                   # momentum, only relevant for SGD
    betas: [0.9, 0.999]             # betas, relevant only for Adam
    weight_decay: 0.0

log:
  savedir: ""                       # dummy, will be overrided by saved/name 
  track: 
    every: 1 
  checkpoint: 
    every: 10000
    model: True 
    optimizer: True
  diagnose: 
    every: 1
    weights: True 
    gradients: True 
    sample: False 
    distribution: True
  wandb: 
    enabled: True 
    entity: "bahngmc-duke-university" 
    project: ""

